optimize wpforms calling
BeAPI/bea-acf-wp-forms pull request #13
Opened 2024-02-02 09:54 UTC by lphoumpakka

2024-02-02 15:42 UTC, ecorica commented on classes/field.php
> +		echo '<select id="wpforms-modal-select-form" name="' . $field['name'] . '">';
sprint ? + manque l'escape ?

2024-02-02 15:42 UTC, ecorica commented on classes/field.php
> +		if ( $field['allow_null'] ) {
check pas si empty ou isset ?

2024-02-02 15:45 UTC, ecorica approved these changes, later dismissed

2024-02-02 15:45 UTC, ecorica commented on classes/field.php
> +			echo '<option value="">' . __( '- Select a form -', 'bea-wp-forms' ) . '</option>';
régénrer les trads

2024-02-02 15:50 UTC, petitphp requested changes

2024-02-02 15:50 UTC, petitphp commented on classes/field.php
> +			printf( '<option value="%d" %s>%s</option>', $form->ID, $selected, esc_html( $form->post_title ) );
Manque le `esc_attr` ici.

2024-02-02 16:03 UTC, ecorica approved these changes, later dismissed

2024-02-02 16:24 UTC, Rahe commented on classes/field.php
> +		$forms = wpforms()->form->get( '' );
Ca n'aide pas dans la perf, là on cherche les champs à chaque render.
Donc j'ai 40 fois le champs dans la page : 40 appels à cette méthode.
Il faut la stocker comme précédemment, mais ne la chercher que si elle n'est pas remplie encore.

2024-02-02 18:08 UTC, lphoumpakka commented on classes/field.php
> +		$forms = wpforms()->form->get( '' );
J'ai fait une modif @Rahe. Dispo pour en parler IRL ce sera plus plus rapide.

2024-02-06 16:44 UTC, lphoumpakka commented
Cette fois-ci est la bonne @Rahe

2024-02-06 17:27 UTC, Rahe commented on classes/field.php
> +			'choices' => array(
Attention tu es revenu en arrière sur les tableaux

2024-02-06 17:27 UTC, Rahe approved these changes, later dismissed

2024-02-07 09:42 UTC, petitphp commented on classes/main.php
> +	protected $wp_forms;
Cette propriété n'est pas utilisée, il faudrait la supprimer.

2024-02-07 09:42 UTC, petitphp submitted a review, later dismissed
Il reste une propriété à supprimer sinon RAS.

2024-02-07 10:06 UTC, petitphp approved these changes
Merci

2024-02-07 10:32 UTC, lphoumpakka commented on classes/field.php
> +			'choices' => array(
j'ia modif

2024-02-07 10:33 UTC, merged